=begin
#Merge ATS API

#The unified API for building rich integrations with multiple Applicant Tracking System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MergeATSClient::AvailableModelsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AvailableModelsApi' do
  before do
    # run before each test
    @api_instance = MergeATSClient::AvailableModelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AvailableModelsApi' do
    it 'should create an instance of AvailableModelsApi' do
      expect(@api_instance).to be_instance_of(MergeATSClient::AvailableModelsApi)
    end
  end

  # unit tests for available_models_retrieve
  # Returns a list of models and actions available for an account.
  # @param x_account_token Token identifying the end user.
  # @param [Hash] opts the optional parameters
  # @return [AvailableActionsSerialzier]
  describe 'available_models_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
