=begin
#Merge ATS API

#The unified API for building rich integrations with multiple Applicant Tracking System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MergeATSClient::ForceResyncApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ForceResyncApi' do
  before do
    # run before each test
    @api_instance = MergeATSClient::ForceResyncApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ForceResyncApi' do
    it 'should create an instance of ForceResyncApi' do
      expect(@api_instance).to be_instance_of(MergeATSClient::ForceResyncApi)
    end
  end

  # unit tests for sync_status_resync_create
  # Force re-sync of all models. This is only available for organizations on Merge&#39;s Grow and Expand plans.
  # @param x_account_token Token identifying the end user.
  # @param [Hash] opts the optional parameters
  # @return [SyncStatus]
  describe 'sync_status_resync_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
