=begin
#Merge ATS API

#The unified API for building rich integrations with multiple Applicant Tracking System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MergeATSClient::JobsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JobsApi' do
  before do
    # run before each test
    @api_instance = MergeATSClient::JobsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobsApi' do
    it 'should create an instance of JobsApi' do
      expect(@api_instance).to be_instance_of(MergeATSClient::JobsApi)
    end
  end

  # unit tests for jobs_create
  # Creates a &#x60;Job&#x60; object with the given values.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_account_token Token identifying the end user.
  # @option opts [Boolean] :run_async Whether or not third-party updates should be run asynchronously.
  # @option opts [Job] :job 
  # @return [Job]
  describe 'jobs_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for jobs_destroy
  # Deletes a &#x60;Job&#x60; object with the given &#x60;id&#x60;.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_account_token Token identifying the end user.
  # @option opts [Boolean] :run_async Whether or not third-party updates should be run asynchronously.
  # @return [Job]
  describe 'jobs_destroy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for jobs_list
  # Returns a list of &#x60;Job&#x60; objects.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_account_token Token identifying the end user.
  # @option opts [DateTime] :created_after If provided, will only return objects created after this datetime.
  # @option opts [DateTime] :created_before If provided, will only return objects created before this datetime.
  # @option opts [Integer] :cursor The pagination cursor value.
  # @option opts [String] :expand Which relations should be returned in expanded form.
  # @option opts [DateTime] :modified_after If provided, will only return objects modified after this datetime.
  # @option opts [DateTime] :modified_before If provided, will only return objects modified before this datetime.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @option opts [String] :remote_id The API provider&#39;s ID for the given object.
  # @return [PaginatedJobList]
  describe 'jobs_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for jobs_partial_update
  # Updates a &#x60;Job&#x60; object with the given &#x60;id&#x60;.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_account_token Token identifying the end user.
  # @option opts [Boolean] :run_async Whether or not third-party updates should be run asynchronously.
  # @option opts [PatchedJob] :patched_job 
  # @return [Job]
  describe 'jobs_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for jobs_retrieve
  # Returns a &#x60;Job&#x60; object with the given &#x60;id&#x60;.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_account_token Token identifying the end user.
  # @option opts [String] :expand Which relations should be returned in expanded form.
  # @return [Job]
  describe 'jobs_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
