=begin
#Merge ATS API

#The unified API for building rich integrations with multiple Applicant Tracking System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'date'
require 'time'

module MergeATSClient
  class RaceEnum
    AMERICAN_INDIAN_OR_ALASKAN_NATIVE = "AMERICAN_INDIAN_OR_ALASKAN_NATIVE".freeze
    ASIAN = "ASIAN".freeze
    BLACK_OR_AFRICAN_AMERICAN = "BLACK_OR_AFRICAN_AMERICAN".freeze
    HISPANIC_OR_LATINO = "HISPANIC_OR_LATINO".freeze
    WHITE = "WHITE".freeze
    NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER = "NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER".freeze
    TWO_OR_MORE_RACES = "TWO_OR_MORE_RACES".freeze
    DECLINE_TO_SELF_IDENTIFY = "DECLINE_TO_SELF_IDENTIFY".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = RaceEnum.constants.select { |c| RaceEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #RaceEnum" if constantValues.empty?
      value
    end
  end
end
