=begin
#Merge ATS API

#The unified API for building rich integrations with multiple Applicant Tracking System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'date'
require 'time'

module MergeATSClient
  class RequestFormatEnum
    JSON = "JSON".freeze
    XML = "XML".freeze
    MULTIPART = "MULTIPART".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = RequestFormatEnum.constants.select { |c| RequestFormatEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #RequestFormatEnum" if constantValues.empty?
      value
    end
  end
end
