=begin
#Merge ATS API

#The unified API for building rich integrations with multiple Applicant Tracking System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module MergeATSClient
  class UrlTypeEnum
    PERSONAL = "PERSONAL".freeze
    COMPANY = "COMPANY".freeze
    PORTFOLIO = "PORTFOLIO".freeze
    BLOG = "BLOG".freeze
    SOCIAL_MEDIA = "SOCIAL_MEDIA".freeze
    OTHER = "OTHER".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = UrlTypeEnum.constants.select { |c| UrlTypeEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #UrlTypeEnum" if constantValues.empty?
      value
    end
  end
end
