=begin
#Merge ATS API

#The unified API for building rich integrations with multiple Applicant Tracking System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'cgi'

module MergeATSClient
  class WebhookReceiversApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Creates a `WebhookReceiver` object with the given values.
    # @param x_account_token [String] Token identifying the end user.
    # @param webhook_receiver_request [WebhookReceiverRequest] 
    # @param [Hash] opts the optional parameters
    # @return [WebhookReceiver]
    def webhook_receivers_create(x_account_token, webhook_receiver_request, opts = {})
      data, _status_code, _headers = webhook_receivers_create_with_http_info(x_account_token, webhook_receiver_request, opts)
      data
    end

    # Creates a &#x60;WebhookReceiver&#x60; object with the given values.
    # @param x_account_token [String] Token identifying the end user.
    # @param webhook_receiver_request [WebhookReceiverRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(WebhookReceiver, Integer, Hash)>] WebhookReceiver data, response status code and response headers
    def webhook_receivers_create_with_http_info(x_account_token, webhook_receiver_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: WebhookReceiversApi.webhook_receivers_create ...'
      end
      # verify the required parameter 'x_account_token' is set
      if @api_client.config.client_side_validation && x_account_token.nil?
        fail ArgumentError, "Missing the required parameter 'x_account_token' when calling WebhookReceiversApi.webhook_receivers_create"
      end
      # verify the required parameter 'webhook_receiver_request' is set
      if @api_client.config.client_side_validation && webhook_receiver_request.nil?
        fail ArgumentError, "Missing the required parameter 'webhook_receiver_request' when calling WebhookReceiversApi.webhook_receivers_create"
      end
      # resource path
      local_var_path = '/webhook-receivers'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      header_params[:'X-Account-Token'] = x_account_token

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(webhook_receiver_request)

      # return_type
      return_type = opts[:debug_return_type] || 'WebhookReceiver'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['tokenAuth']

      new_options = opts.merge(
        :operation => :"WebhookReceiversApi.webhook_receivers_create",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WebhookReceiversApi#webhook_receivers_create\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Returns a list of `WebhookReceiver` objects.
    # @param x_account_token [String] Token identifying the end user.
    # @param [Hash] opts the optional parameters
    # @return [Array<WebhookReceiver>]
    def webhook_receivers_list(x_account_token, opts = {})
      data, _status_code, _headers = webhook_receivers_list_with_http_info(x_account_token, opts)
      data
    end

    # Returns a list of &#x60;WebhookReceiver&#x60; objects.
    # @param x_account_token [String] Token identifying the end user.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<WebhookReceiver>, Integer, Hash)>] Array<WebhookReceiver> data, response status code and response headers
    def webhook_receivers_list_with_http_info(x_account_token, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: WebhookReceiversApi.webhook_receivers_list ...'
      end
      # verify the required parameter 'x_account_token' is set
      if @api_client.config.client_side_validation && x_account_token.nil?
        fail ArgumentError, "Missing the required parameter 'x_account_token' when calling WebhookReceiversApi.webhook_receivers_list"
      end
      # resource path
      local_var_path = '/webhook-receivers'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      header_params[:'X-Account-Token'] = x_account_token

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<WebhookReceiver>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['tokenAuth']

      new_options = opts.merge(
        :operation => :"WebhookReceiversApi.webhook_receivers_list",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WebhookReceiversApi#webhook_receivers_list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
