=begin
#Merge ATS API

#The unified API for building rich integrations with multiple Applicant Tracking System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeATSClient::AsyncPassthroughReciept
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeATSClient::AsyncPassthroughReciept do
  let(:instance) { MergeATSClient::AsyncPassthroughReciept.new }

  describe 'test an instance of AsyncPassthroughReciept' do
    it 'should create an instance of AsyncPassthroughReciept' do
      expect(instance).to be_instance_of(MergeATSClient::AsyncPassthroughReciept)
    end
  end
  describe 'test attribute "async_passthrough_receipt_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
