=begin
#Merge ATS API

#The unified API for building rich integrations with multiple Applicant Tracking System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeATSClient::OverallRecommendationEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OverallRecommendationEnum' do
  before do
    # run before each test
    @instance = MergeATSClient::OverallRecommendationEnum.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OverallRecommendationEnum' do
    it 'should create an instance of OverallRecommendationEnum' do
      expect(@instance).to be_instance_of(MergeATSClient::OverallRecommendationEnum)
    end
  end
end
