=begin
#Merge ATS API

#The unified API for building rich integrations with multiple Applicant Tracking System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeATSClient::RemoteKeyForRegenerationRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeATSClient::RemoteKeyForRegenerationRequest do
  let(:instance) { MergeATSClient::RemoteKeyForRegenerationRequest.new }

  describe 'test an instance of RemoteKeyForRegenerationRequest' do
    it 'should create an instance of RemoteKeyForRegenerationRequest' do
      expect(instance).to be_instance_of(MergeATSClient::RemoteKeyForRegenerationRequest)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
