=begin
#Merge ATS API

#The unified API for building rich integrations with multiple Applicant Tracking System platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeATSClient::VisibilityEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeATSClient::VisibilityEnum do
  let(:instance) { MergeATSClient::VisibilityEnum.new }

  describe 'test an instance of VisibilityEnum' do
    it 'should create an instance of VisibilityEnum' do
      expect(instance).to be_instance_of(MergeATSClient::VisibilityEnum)
    end
  end
end
